Running Emacs in iTerm2, so Emacs is running on a Linux VM and I'm accessing it through iTerm2 in OS X.

* Remapping/translating keys

The keys are re-mapped through iTerm2, with Command keys acting as Control (in OS X I just use ~(setq mac-command-modifier 'control)~), and Option keys sending +Esc, so they work perfectly as Meta. That was a huge problem before... I like hitting M-<key>, having to hit the Esc key does not work for me.

On the EmacsWiki it suggests using keycode 66 for Caps Lock:
 http://www.emacswiki.org/emacs/CapsKey#toc6

That is for Xmodmap though, I'm using Seil to change the keys on OS X and I'm not sure all of the keycodes are the same. I tried using a bunch of keycodes that Seil recognized, but Emacs didn't seem to recognize them, so I'm using keycode 66, which Emacs recognizes as 'C-]' which is bound to ~abort-recursive-edit~, but I just mash C-g anyway, so I think getting rid of that keybinding will be fine. 

So C-] is now translsated to Hyper key, so I can use Hyper key in iTerm2. 

... no this C-] business isn't working. It's fine if I want to type say Caps Lock to trigger a hyper event and then a key, but not if I want to use Capslock as part of a keychord as 'hyper. 

The normal control key on the OS X keyboard functions as Command still, so I can use it to cut and paste to the OS X clipboard, in and out of the terminal. 

Last thing is that iTerm2 is set to ignore modifier remapping on Command-TAB, so I can still use Command-TAB to switch windows.

* File changed on disk
  I keep getting messages that the file has changed on disk which is really, really annoying. I was thinking it was Dropbox doing it, but I turned off Dropbox and it seems to still be happening, so maybe it's just an issue with shared folders/symbolic links in general.
  I'll have to do some invesitgation and experimentation.

  Anyway, if I'm using Emacs in the terminal, now there is no reason at all to be working out of a shared folder, I was doing it mostly to edit on OS X and execute on Linux, but now I do both on Linux.
